apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.10.3
    helm:
      values: |
        adminUser: admin
        adminPassword: admin

        service:
          type: ClusterIP
          port: 80

        persistence:
          enabled: true
          size: 10Gi
          storageClassName: "local-path"

        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web # If using Traefik
          hosts:
            - grafana.127.0.0.1.nip.io
            - grafana.192.168.0.21.nip.io
          paths:
            - /
          tls: []  # Disable TLS since you're using HTTP or configure TLS if necessary

        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                access: proxy
                url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9100
                isDefault: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring