apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - PruneLast=true
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 70.0.2
    helm:
      values: |
        prometheus:
          prometheusSpec:
            retention: 365d
            retentionSize: 10GB
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  storageClassName: "local-path"
                  resources:
                    requests:
                      storage: 10Gi

          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
            hosts:
              - prometheus.127.0.0.1.nip.io
              - prometheus.192.168.0.21.nip.io
            paths:
              - /
            tls: []  # No TLS, plain HTTP

        grafana:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring