apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus-community
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 27.5.1
    helm:
      values: |
        server:
          persistentVolume:
            enabled: true
            size: 10Gi  # 10GB storage for Prometheus data
          retention: 365d  # Keep data for 365 days
          retentionSize: 10GB  # Limit data retention to 10GB

          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
            hosts:
              - prometheus.127.0.0.1.nip.io
              - prometheus.192.168.0.21.nip.io
            paths:
              - /
            tls: []  # No TLS, plain HTTP

          service:
            type: ClusterIP
            port: 80
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring