apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tweets
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
  source:
    path: argocd/charts/tweets/helm
    repoURL: https://github.com/MoonChel/lab.git
    targetRevision: master
    helm:
      valueFiles:
        - ../version/listener-image.yaml
        - ../version/api-image.yaml
      values: |
        namespace: tweets

  destination:
    server: "https://kubernetes.default.svc"
    namespace: tweets