apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-listener
  template:
    metadata:
      labels:
        app: telegram-listener
    spec:
      volumes:
        - name: telegram-session
          persistentVolumeClaim:
            claimName: telegram-session-pvc
      containers:
        - name: listener-container
          image: {{ .Values.listener.image }}
          volumeMounts:
            - name: telegram-session
              mountPath: /app/session
          env:
            - name: TELEGRAM_API_ID
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-secrets
                  key: TELEGRAM_API_ID
            - name: TELEGRAM_API_HASH
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-secrets
                  key: TELEGRAM_API_HASH
            - name: TELEGRAM_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-secrets
                  key: TELEGRAM_SESSION_TOKEN
            - name: WEBHOOK_URL
              value: http://fastapi-service.{{ .Values.namespace }}.svc.cluster.local