apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-listener
  template:
    metadata:
      labels:
        app: telegram-listener
    spec:
      containers:
        - name: listener-container
          image: {{ .Values.listener.image }}
          envFrom:
            - secretRef:
              name: telegram-bot-secrets
          env:
            - name: WEBHOOK_URL
              value: http://fastapi-service.{{ .Values.namespace }}.svc.cluster.local