apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegram-session-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi