---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: telegram-bot-secrets
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgCf69hULbNBu3Vlly53lSL5/60lWV4CfNKdwB8n959YWibN740vu+20gUq3TkoXsR9LAVWzugoonWqErZq9l87eXBl36y1JcVz90Sk365hoUeSDyWS10HubLlnXpa5zfLpCVlLm7MpbDwQ9HMGGaxkEd/5uTZuIWGblGlHYkYpRSgpM3dXr6T0ozzMCNMqhOHYXZrIDVcDQZeptYOWI2kZ+Oz+kvLTnayXDyXM8xn/b/3KyqQL3xfzOkt/ivHdES6FPU8RVAEXo30yseup4obnItqSjPBfLiEIE3hxZjuG2Kq78zhcsMsaZXl6t8/bWQxQPoLO6oBK9cZXSJ6BlMkfvrluGt/xkw7N/Nq5MYkHMWSPl8pZMzhIY1+/OHBRioRq8Pe+o9y9P0Ky086c/+JhjMeNaLufd6GwTHOM51pkhxt1jjgyRs9l+dRg4PqCm5umYDB7XXmj9Nufv0BAkCXwexfQGwaphwpCycKMukXkLuZoWxMnEYonSqvzlevLtusQ2DMBGf7ySh+RStlEYYN3P3wOYY96GduxWJNZzn24CW5x0A5hHN0/2JlfWx5v4kvfkMVf9txxA2WDgrWI5mCnmNzRoheRjaUOr+jEQS2By0WU9hbHEycsV47aorII6FKdM9DQF0VrGbdyFRtrHFGtcICQXPCDkGVJlHsP9b6GjJrJy4bBYHI5Ml/In608TqTLuXF98n7vPy/kZ2q6eggZtRnCHKm6Ml7gY9j0m+oJLpV82nhqGIvNcZla78FBijw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: telegram-bot-secrets
