---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-bot-secrets
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgBOZKIt+XbSwr6/6YgCfxMHcJ3uazs+sBskFp7vTcAHdmxSUCfF/MMjl30+lFBw9Fvhesx1sf/UombW+5Ce5H+p20i2TIwyAcpgB7z9glpjpNyKZAt8jPm0lrlXWatF+xH5KAiIDUwNHIaveKVxUvns8sbV43rWcxpwL+RR32eijwjsoJhaA1T+X0Z6Hq4dYqwV0QSuqLJKtMDwfIjMgcLRN5a7W7R2PCfsMQM+FzjjmL1d/pKu/ZmRS9lvS9+xXjaO6iZqnQdgvN4z5jFZv47EeTM8X7xA6vMw/od+SKoAAiwQC6NzDnylUbr5wfOpNOuekmboNmltejoJ8KhyWIUkXS4FFAEkVLOD1qrzxRyxEONSmI0Sduv6jeMtbRU/lx7mqoh8D1KvhlW3M/U6DVQ9ksQrPM/l8wIJF98N9XeerAL8JxAgug7HUjV3LL9778j/k7r8kmrf0gaZUGEVMl8HyBNtwmMXRKKbsC9Mqsm/eBy6jiH2FRZ6r71Q9rXRs0ai9yEpiMIjPk/hZ0Hh0AHJ7efYELbsJg58U6kL4NIxJ258EJbzBc4Yra/1vOtOBUL382PSxQuOlANhmM+b6510I2idgZUyxpdGzwEmcx3SlWF3R5mg/Bivf4g6lwwOFK5154loG8TKgyb7TeyHKaHs1AQBdD0NdG7ccGNohNwZ4VC2eE+fXKKGBOcpFhRv3x7YYlRoE1WCshY613hW1BihgKPZe2ezirvBu4W6hYeYSJP8t5UBacXYxBI2CZmNoQ==
  template:
    metadata:
      creationTimestamp: null
      name: telegram-bot-secrets
