apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi-app
spec:
  selector:
    app: fastapi-app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
